/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vunit_32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

//register address
//rcc
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_IOPAEN (1<<2)

//GPIO
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_CRL *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_IDR *(volatile uint32_t *)(GPIOA_BASE + 0x08)

#define GPIOA13 (1UL<<13)

#define GPIOB_BASE 0x40010C00
#define GPIOB_CRH *(volatile uint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_CRL *(volatile uint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_ODR *(volatile uint32_t *)(GPIOB_BASE + 0x0C)
#define GPIOB_IDR *(volatile uint32_t *)(GPIOB_BASE + 0x08)

void clock_init()
{
	//Enable clock GPIOA
	RCC_APB2ENR |= RCC_IOPAEN;
	//Enable clock GPIOB
	RCC_APB2ENR |= (1<<3);

}

void GPIO_init()
{
	GPIOA_CRL = 0x0;
	GPIOB_CRL = 0x0;
	GPIOA_CRH = 0x0;
	GPIOA_CRL = 0x0;

	//PA1 input highZ
	GPIOA_CRL |= 1<<6;

	//PB1 output push mode
	GPIOB_CRL |= 1<<4;

	//PA13 input highZ
	GPIOA_CRH |= 1<<22;

	//PB13 output push-mode
	GPIOB_CRH |= 1<<20;
}

void my_wait(int x)
{
	unsigned int i,j;
	for ( i =0 ; i < x ; i++)
		for ( j=0 ; j<x;j++);
}

int main(void)
{
	clock_init();
	GPIO_init();


	while(1)
	{
		//PA1 press
		if(((GPIOA_IDR &= 1<<1) >> 1) == 0) // pressed
		{
			GPIOB_ODR ^= 1<<1;
			while(((GPIOA_IDR &= 1<<1) >> 1) == 0); // single press
		}

		//PA13 pressed
		if( ((GPIOA_IDR &= 1<<13)>>13)== 1)
		{
			GPIOB_ODR ^= 1<<13;
		}
		my_wait(300);
	}
}

