/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stm32f103x6.h>
#include <Stm32_F103C6_gpio_driver.h>
#include <Stm32_F103C6_EXTI_driver.h>
#include <STM32F103C6_LCD.h>
#include <STM32F103C6_KEYPAD.h>

unsigned int CPU_ControlRegRead_Value = 0;
unsigned int CPU_ISPRRegRead_Value = 0;

unsigned int IRQ_Flag = 0 ;


void EXT9_CallBack(void)
{
	//	LCD_clearScreen();
	IRQ_Flag = 1;
	LCD_displayString("IRQ happened successfully!!");

	__asm__("nop \n\t nop \n\t nop");

	__asm__("MRS %[out0],IPSR"
			:[out0] "=r" (CPU_ISPRRegRead_Value));

	__asm__("nop \n\t nop \n\t nop");
}


int main(void)
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	LCD_init();
	LCD_clearScreen();

	EXTI_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN = EXTI9PB9;
	EXTI_CFG.EXTI_Trigger = EXTI_Trigger_Rising;
	EXTI_CFG.P_IRQ_CallBack = EXT9_CallBack ;
	EXTI_CFG.IRQ_EN = EXTI_IRQ_Enable ;

	MCAL_EXTI_GPIO_Init(&EXTI_CFG);

	IRQ_Flag = 1;


	__asm__("nop \n\t nop \n\t nop");

	//add VAL3 , VAL1 , VAL2
	__asm__("MRS %[out0],CONTROL"
			: [out0] "=r" (CPU_ControlRegRead_Value) );

	__asm__("nop \n\t nop \n\t nop");

	while(1)
	{
		if(IRQ_Flag)
		{
			LCD_clearScreen();
			IRQ_Flag=0;
		}

	}
}

