/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stm32f103x6.h>
#include <Stm32_F1103C6_gpio_driver.h>
#include <Stm32_F1103C6_EXTI_driver.h>
#include <Stm32_F1103C6_USART_driver.h>
#include <STM32F103C6_LCD.h>
#include <STM32F103C6_KEYPAD.h>

void clock_init()
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}
unsigned char ch ;


void USART_IRQ_CallBack(void)
{
	MCAL_UART_ReceiveData(USART1, &ch, Disable);
	MCAL_UART_SendData(USART1, &ch, Enable);


}



int main(void)
{

	clock_init();
	UART_Config_t UART ;
	UART.BAUDRATE = UART_BaudRate_115200 ;
	UART.FlowCTRL = UART_FlowCTRL_None ;
	UART.IRQ_En = UART_IRQ_EN_RXNEIE ;
	UART.USART_MODE = UART_MODE_TX_RX ;
	UART.Parity = UART_Parity_Disable ;
	UART.Payload_Length = UART_PayloadLength_8b ;
	UART.StopBits = UART_StopBits_1b ;
	UART.P_IRQ_CallBack =  USART_IRQ_CallBack;

	MCAL_UART_Init(USART1, &UART);
	MCAL_UART_GPIO_SetPins(USART1);

	while(1)
	{


	}
}
