/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stm32f103x6.h>
#include <Stm32_F103C6_gpio_driver.h>
#include <Stm32_F103C6_EXTI_driver.h>
#include <STM32F103C6_LCD.h>
#include <STM32F103C6_KEYPAD.h>



unsigned int TASKA_flag, TASKB_flag, IRQ_Flag = 0;

#define TaskA_Stack_Size 100 //100Bytes
#define TaskB_Stack_Size 100 //100Bytes

extern int _estack ;
//Main Stack
unsigned int _S_MSP = &_estack;
unsigned int _E_MSP;

//Process Stack Task A
unsigned int _S_PSP_TA;
unsigned int _E_PSP_TA;

//Process Stack Task B
unsigned int _S_PSP_TB;
unsigned int _E_PSP_TB;

#define OS_SET_PSP(add)			__asm volatile("mov r0,%0 \n\t msr PSP,r0" : : "r" (add) )
#define OS_SWITCH_SP_to_PSP		__asm volatile("mrs r0,CONTROL \n\t mov r1,#0x02 \n\t orr r0,r1,r1 \n\t msr CONTROL,r0")
#define OS_SWITCH_SP_to_MSP		__asm volatile("mrs r0,CONTROL \n\t mov r1,#0x05 \n\t and r0,r0,r1 \n\t msr CONTROL,r0")

#define OS_Generate_Exception	__asm volatile("SVC #0x3")


enum CPUAccessLevel {
	privileged,
	unprivileged
};

void SVC_Handler()
{
	SWITCH_CPU_AccessLevel(privileged);
}
void SWITCH_CPU_AccessLevel(enum CPUAccessLevel level)
{
	switch (level)
	{
	case privileged:
		//Reset bit 0 in CONTROL register
		__asm("mrs r3, CONTROL  \n\t"
			  "lsr r3, r3, #0x1 \n\t"
			  "lsl r3, r3, #0x1 \n\t"
			  "msr CONTROL, r3");
		break;

	case unprivileged:
		//Set bit 0 in CONTROL register
		__asm("mrs r3, CONTROL    \n\t"
			  "orr r3, r3, #0x1   \n\t"
			  "msr CONTROL, r3");
		break;
	}
}


void EXT9_CallBack(void)
{
	if(IRQ_Flag == 0)
	{
		TASKA_flag = 1;
		IRQ_Flag = 1;
	}else if (IRQ_Flag == 1)
	{
		TASKB_flag = 1;
		IRQ_Flag = 0;
	}
}

int TaskA(int a, int b, int c)
{
	return a+b+c;
}
int TaskB(int a, int b, int c, int d)
{
	return a+b+c;
}
void MainOs()
{
	_E_MSP = (_S_MSP - 512) ;

	//Task A
	_S_PSP_TA = (_E_MSP - 8) ;
	_E_PSP_TA = (_S_PSP_TA - TaskA_Stack_Size) ;

	//Task B
	_S_PSP_TB = (_E_PSP_TA - 8) ;
	_E_PSP_TB = (_S_PSP_TB - TaskB_Stack_Size) ;

	while(1)
	{
		__asm("nop");

		if(TASKA_flag == 1)
		{
			//Set PSP Register == _S_PSP_TA
			OS_SET_PSP(_S_PSP_TA);

			//SP -> PSP
			OS_SWITCH_SP_to_PSP;

			//switch from privileged -> unprivileged
			SWITCH_CPU_AccessLevel(unprivileged);

			TASKA_flag = TaskA(1,2,3) ;

			//switch from unprivileged -> privileged
			OS_Generate_Exception;
			//SP -> MSP
			OS_SWITCH_SP_to_MSP;

		}else if(TASKB_flag == 1)
		{
			//Set PSP Register == _S_PSP_TB
			OS_SET_PSP(_S_PSP_TB);

			//SP -> PSP
			OS_SWITCH_SP_to_PSP;

			//switch from privileged -> unprivileged
			SWITCH_CPU_AccessLevel(unprivileged);

			TASKB_flag = TaskB(1,2,3,4);

			//switch from unprivileged -> privileged
			OS_Generate_Exception;

			//SP -> MSP
			OS_SWITCH_SP_to_MSP;

		}
	}
}

int main(void)
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();



	EXTI_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN = EXTI9PB9;
	EXTI_CFG.EXTI_Trigger = EXTI_Trigger_Rising;
	EXTI_CFG.P_IRQ_CallBack = EXT9_CallBack ;
	EXTI_CFG.IRQ_EN = EXTI_IRQ_Enable ;
	MCAL_EXTI_GPIO_Init(&EXTI_CFG);

	MainOs();
	IRQ_Flag = 1;

	while(1)
	{
		if(IRQ_Flag)
		{
			IRQ_Flag=0;
		}

	}
}

