/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif




#include <stm32f103x6.h>
#include <Stm32_F103C6_gpio_driver.h>
#include <Stm32_F103C6_EXTI_driver.h>
#include <Stm32_F103C6_USART_driver.h>
#include <STM32F103C6_LCD.h>
#include <STM32F103C6_KEYPAD.h>
#include <Stm32_F103C6_SPI_driver.h>

#define MCU_act_as_Master
//#define MCU_act_as_Slave


uint16_t ch ;
//
//void SPI1_IRQ_CallBack(S_IRQ_SRC irq_src)
//{
//#ifdef MCU_act_as_Slave
//	if(irq_src.RXNE)
//	{
//		ch = 0xf;
//		MCAL_SPI_Tx_Rx(SPI1, &ch, polling_Enable);
//		MCAL_UART_SendData(USART1, &ch, Enable);
//	}
//#endif
//}

void USART_IRQ_CallBack(void)
{
#ifdef MCU_act_as_Master
	MCAL_UART_ReceiveData(USART1, &ch, Disable);
	MCAL_UART_SendData(USART1, &ch, Enable);

	//send to spi
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 0);
	MCAL_SPI_Tx_Rx(SPI1, &ch, polling_Enable);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 1);
#endif
}

void clock_init()
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}

int main(void)
{

	clock_init();
	UART_Config_t UART ;
	GPIO_PinConfig_t PinConfig;

	//------------UART INIT--------------------
	//PA9	Tx
	//PA10	RX
	//PA11	CTS
	//PA12	RTS
	UART.BAUDRATE = UART_BaudRate_115200 ;
	UART.FlowCTRL = UART_FlowCTRL_None ;
	UART.IRQ_En = UART_IRQ_EN_RXNEIE ;
	UART.USART_MODE = UART_MODE_TX_RX ;
	UART.Parity = UART_Parity_Disable ;
	UART.Payload_Length = UART_PayloadLength_8b ;
	UART.StopBits = UART_StopBits_1b ;
	UART.P_IRQ_CallBack =  USART_IRQ_CallBack;

	MCAL_UART_Init(USART1, &UART);
	MCAL_UART_GPIO_SetPins(USART1);


	//------------SPI INIT--------------------
	//PA4	NSS
	//PA5	SCK
	//PA6	MISO
	//PA7	MSIO
	SPI_Config_t SPI1CFG;

	//common configuration
	SPI1CFG.CLK_Phase = SPI_CLK_Phase_2nd_Edge;
	SPI1CFG.CLK_Polarity = SPI_CLK_Polarity_High_idle;
	SPI1CFG.Data_Size = SPI_Data_Size_8Bit;
	SPI1CFG.Frame_Format = SPI_Frame_Format_MSB_First;
	SPI1CFG.SPI_Baudrate_Prescalar = SPI_Baudrate_Prescalar_8;
	SPI1CFG.Communication_MODE = SPI_DIRECTION_2Lines;

#ifdef MCU_act_as_Master
	SPI1CFG.Device_Mode = SPI_DEVICE_MODE_MASTER;
	SPI1CFG.IRQ_Enable = SPI_IRQ_Enable_None;
	SPI1CFG.NSS = SPI_NSS_SW_InternalSoft_Set;
	SPI1CFG.P_IRQ_CallBack = NULL;

	//configure Select Slave on PA4 by GPIO
	PinConfig.GPIO_PinNumber = GPIO_PIN_4;
    PinConfig.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
    PinConfig.GPIO_Output_Speed = GPIO_SPEED_10M;
    MCAL_GPIO_Init(GPIOA, &PinConfig);

    MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 1);
#endif

//#ifdef MCU_act_as_Slave
//	SPI1CFG.Device_Mode = SPI_DEVICE_MODE_SLAVE;
//	SPI1CFG.IRQ_Enable = SPI_IRQ_Enable_RXNEIE;
//	SPI1CFG.NSS = SPI_NSS_HW_SLAVE;
//	SPI1CFG.P_IRQ_CallBack = SPI1_IRQ_CallBack;
//#endif

	MCAL_SPI_Init(SPI1, &SPI1CFG);
	MCAL_SPI_GPIO_Set_Pins(SPI1);




	while(1)
	{
	}
}
